apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: geolocation
  name: geolocation
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app: geolocation
status:
  loadBalancer: {}
